services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=1234'
      - 'MARIADB_ROOT_PASSWORD=1234'
      - 'MARIADB_USER=root'
      - 'SPRING_JPA_HIBERNATE_DDL-AUTO=create'
    ports:
      - '3306:3306'
